[platformio]
src_dir = code/esp32code

[env:xiao_esp32c3]
platform = espressif32@6.9.0
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.1.0
  links2004/WebSockets@^2.6.1
